[project]
name = "allen-python"
version = "0.1.0"
description = "A modern, type-safe Python library for modeling, normalizing, and manipulating time periods using Allen's Interval Algebra."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Aristóbulo Meneses", email = "aristobulo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.urls]
Homepage = "https://github.com/menecio/allen"
Repository = "https://github.com/menecio/allen"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.7",
]

[tool.uv.build-backend]
module-name = "allen"
source-dir = "src"
include = ["src/allen/py.typed"]
exclude = [
    "tests/**",
    ".github/**",
    ".pytest_cache/**",
    ".ruff_cache/**",
    ".mypy_cache/**",
    "docs/**",
    "*.pyc",
    "__pycache__",
    ".gitignore",
    "uv.lock",
    ".python-version"
]

[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__", "**/.venv/"]
typeCheckingMode = "standard"
pythonVersion = "3.12"
pythonPlatform = "All"

[tool.ruff]
target-version = "py312"
line-length = 120
src = ["src", "tests"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "I",
    "B",
    "RUF",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--cov=allen --cov-fail-under 90 --no-cov-on-fail --cov-report=term-missing -v --strict-markers"
